// Code generated by github.com/prisma/graphqlgen, DO NOT EDIT.

import { GraphQLResolveInfo } from "graphql";
import { Company } from "./models";
type Context = any;

export namespace QueryResolvers {
  export const defaultResolvers = {};

  export type HelloResolver = (
    parent: undefined,
    args: {},
    ctx: Context,
    info: GraphQLResolveInfo
  ) => string | null | Promise<string | null>;

  export interface Type {
    hello: (
      parent: undefined,
      args: {},
      ctx: Context,
      info: GraphQLResolveInfo
    ) => string | null | Promise<string | null>;
  }
}

export namespace MutationResolvers {
  export const defaultResolvers = {};

  export interface ArgsAddCompany {
    name: string | null;
  }

  export type AddCompanyResolver = (
    parent: undefined,
    args: ArgsAddCompany,
    ctx: Context,
    info: GraphQLResolveInfo
  ) => Company | null | Promise<Company | null>;

  export interface Type {
    addCompany: (
      parent: undefined,
      args: ArgsAddCompany,
      ctx: Context,
      info: GraphQLResolveInfo
    ) => Company | null | Promise<Company | null>;
  }
}

export namespace CompanyResolvers {
  export const defaultResolvers = {
    name: (parent: Company) => parent.name
  };

  export type NameResolver = (
    parent: Company,
    args: {},
    ctx: Context,
    info: GraphQLResolveInfo
  ) => string | null | Promise<string | null>;

  export interface Type {
    name: (
      parent: Company,
      args: {},
      ctx: Context,
      info: GraphQLResolveInfo
    ) => string | null | Promise<string | null>;
  }
}

export interface Resolvers {
  Query: QueryResolvers.Type;
  Mutation: MutationResolvers.Type;
  Company: CompanyResolvers.Type;
}
